### ISSUE TITLE
Limitation of log scale

### ISSUE THREAD

**Issue by wellington36** [wellington36/extrapolation_methods#29]
Transforms now convert the sequence of partial sums to a new one on a logarithmic scale. The problem is that, for this, we have to assume that the sequence of partial sums only has positive values, otherwise the logarithm is not defined.

**Comment by wellington36** [comment]
We essentially have two cases, each with its difficulty:

1. There is at least one value in the sequence of partial sums that is negative, but the series itself converges to a positive value.

2. There is at least one value in the sequence of partial sums that is negative, and the series itself converges to a negative value.

If we want to return the value in log-scale in this context, the second case for me makes sense not to work. Since the logarithm is not defined for negative numbers.

**Comment by maxbiostat** [comment]
I think nice behaviour would be something like what the `determinant()` function in R does:

```r
> determinant(matrix(c(0, 1, -2, 0), 2, 2))
$modulus
[1] 0.6931472
attr(,"logarithm")
[1] TRUE

$sign
[1] 1

attr(,"class")
[1] "det"
> determinant(matrix(c(0, 1, 2, 0), 2, 2))
$modulus
[1] 0.6931472
attr(,"logarithm")
[1] TRUE

$sign
[1] -1

attr(,"class")
[1] "det"

```

**Comment by wellington36** [comment]
I think the best way to solve it is from the moment the log is introduced instead of saving just the number, saving a tuple with the sign and the number in module. So we can continue using mpmath, but in this case we have to implement the basic functions for this tuple structure: addition, multiplication, etc. (https://mpmath.org/doc/current/general.html#arithmetic-operations)

_Something like this:_
```python
add(('+', 3.2), ('-', 4.5)) -> ('-', 1.3)

mul(('+', 2), ('-', 3)) -> ('-', 6)

exp(('-', 2), 4) -> ('+', 16)

...
```

**Comment by maxbiostat** [comment]
We'll have to discuss this in more detail. I think there must exist a simpler solution, where one simply tracks the sign of a given number and the performs operations grouping terms by their sign. Instead of having a complicated operation structure. So 'yes to the tuple, no to the operations on tuples' if that makes any sense.

**Comment by wellington36** [comment]
If we ignore the transformation, the problem of calculating the partial sums in log scale can be solved without problem thinking about logsumexp of R for [example](https://mc-stan.org/docs/2_26/stan-users-guide/log-sum-of-exponentials.html). But the problem is how to do this on log-scale and preserving the sign:

Let \{S_n\} be a sequence of numbers in the form (sign(x), log(|x|)), apply a transformation like:

$$
	T_n = 2 S_n - S_{n/2}
$$

or

$$
	T_n = \frac{S_{n-1}S_{n+1} - S_{n}^2}{S_{n+1} - 2 S_{n} + S_{n-1}}.
$$

And the equality $\lim(T_n) = \lim (S_n)$ must hold.

**Comment by wellington36** [comment]
I haven't found a simple way to do it yet. In fact, there is, but I think it would be more work in the long run. Given that, we have very complex transformations. In the case of creating the operations, the part has 2 points that I find interesting:
- Python allows us to define these operations without having to change the code itself, which I think adding or removing some transformation is easier;
- The other point is that the operations will be carried out as usual, care is taken with the sign of each operation;

As an example of what it would be. We can store the sign and number in modulus as a class. Thus ```__operation__``` defines how the operation should be done (in this case the `+`):

```python
from mpmath import log

class LogNumber:
    def __init__(self, sign, num):
        self.sign = sign		# sign
        self.num = num			# non-negative number

    def __add__(self, other):
        if type(other) == LogNumber:
            max_num = max([self.num, other.num])

            if self.sign == other.sign or self.num == max_num:
                return LogNumber(self.sign, max_num + log(exp(self.num - max_num) + exp(other.num - max_num)))
            else:
                return LogNumber(other.sign, max_num + log(exp(other.num - max_num) - exp(self.num - max_num)))

        else:
            return LogNumber(self.sign, self.num + other)
            
    def value(self):	# convert to tuple object
        if self.sign == -1:
            return ('-', self.num)
        else:
            return ('+', self.num)
```
And to convert to log-scale we can use a function that applies the log and creates the object:

```python
def create_lognumber(number):
    if number < 0:
        return LogNumber(-1, log(-number))
    else:
        return LogNumber(1, log(number))
```
An example of this path:
```python
    a = create_lognumber(1)
    b = create_lognumber(-4)
    c = create_lognumber(2)

    print(a.value())
    >>> ('+', mpf('0.0'))
    print(b.value())
    >>> ('-', mpf('1.3862943611198906'))
    print(c.value())
    >>> ('+', mpf('0.69314718055994529'))

    print((a + b + c).value())
    >>> ('-', mpf('0.69314718055994529'))
```
Note that, as such, it is not necessary to do ```add(a, add(b, c))``` or anything like that, because we already defined what is to add. A problem like this would be to beware of unexpected cases, for example, ```create_lognumber(0) = Inf``` (but cases like this would also be a caution in other implementations).

*Note:* An implementation sketch can be found [here](https://github.com/wellington36/acceleration_algorithms/blob/negative_log_scale/acceleration/utils.py)
*Note 2:* The only necessary implementation in the current functions is to do the [conversion to this object](https://github.com/wellington36/acceleration_algorithms/blob/20bcb1835b8ee8457a989716ba866487d41f8427/acceleration/emsum2.py#L16), the other work is to implement the usual operations of float numbers in python.

**Comment by wellington36** [comment]
#32 Closes this
